@tool
extends EditorScript
## based on https://github.com/MMqd/uint-shader-hash
const INCLUDE: Array[String] = [
	"// this shader-include file is generated by a macro",
	"// mixing entropy will produce a better result, but possibly introduces some performance costs",
	"// using output dimensions as the initial seed is recommended",
	"// based on https://github.com/MMqd/uint-shader-hash",
	"const uint MAGIC_NUMBERS[7] = uint[7](",
	"\t0x21f0aaadu, 0x7feb352du, 0x846ca68bu,",
	"\t0xd168aaadu, 0xaf723597u, 0x9e485565u, 0xef1d6b47u",
	");",
	"highp uint fix_zero(highp float f) {",
	"\treturn floatBitsToUint(f + uintBitsToFloat(0x00800000u));",
	"}",
	"highp uint hash_uint(highp uint h, highp uint magic) {",
	"\th++; h ^= h >> 16u; h *= magic; return h;",
	"}",
	"highp float uint_to_normalized_float(highp uint h) {",
	"\treturn uintBitsToFloat((h >> 9u) | floatBitsToUint(1.0)) - 1.0;",
	"}",
	"highp float uint_to_signed_float(highp uint h) {",
	"\thighp float f = uintBitsToFloat((h & 0x807FFFFFu) | floatBitsToUint(1.0));",
	"\treturn f - sign(f);",
	"}",
]

func _run() -> void:
	var buffer: Array[String] = INCLUDE.duplicate()

	for i in range(1, 4):
		for j in range(1, 4):
			for k in 4:
				@warning_ignore("integer_division")
				impl_rand(i, j, k / 2, k % 2, buffer)

	var path := (self.get_script() as Script).get_path().get_base_dir() + "/int_rand.gdshaderinc"

	var file := FileAccess.open(path, FileAccess.WRITE)

	for line in buffer:
		file.store_line(line)
	print("saved as: ", path)

	var file_system := EditorInterface.get_resource_filesystem()
	file_system.scan()
	file_system.update_file(path)


func impl_rand(dim_in: int, dim_out: int, mix_entropy: bool, signed: bool, buffer: Array[String]) -> void:
	const TYPE_DIM: Array[String] = ["", "float", "vec2", "vec3", "vec4"]

	var idents := {
		"dim_in": str(dim_in),
		"dim_out": str(dim_out),
		"mix_entropy": "_mix_entropy" if mix_entropy else "",
		"signed": "_signed" if signed else "_normalized",
		"type_in": TYPE_DIM[dim_in],
		"type_out": TYPE_DIM[dim_out],
	}

	buffer.push_back("highp {type_out} rand_dim_{dim_in}_to_{dim_out}{signed}{mix_entropy}({type_in} val, uint seed) {".format(idents))

	if dim_in == 1:
		buffer.push_back("\tuint fixed_0 = fix_zero(val);")
	else:
		for i in dim_in:
			buffer.push_back("\tuint fixed_%d = fix_zero(val[%d]);" % [i, i])

	for i in dim_in:
		buffer.push_back("\tseed = hash_uint(seed + fixed_%d, MAGIC_NUMBERS[%d]);" % [i, i])


	for i in dim_out:
		if mix_entropy and i < dim_in:
			buffer.push_back("\tuint tmp_%d = hash_uint(seed + fixed_%d, MAGIC_NUMBERS[%d]);" % [i, i, i])
		else:
			buffer.push_back("\tuint tmp_%d = hash_uint(seed, MAGIC_NUMBERS[%d]);" % [i, i])

	if dim_out == 1:
		if signed:
			buffer.push_back("\treturn uint_to_signed_float(tmp_0);")
		else:
			buffer.push_back("\treturn uint_to_normalized_float(tmp_0);")
	else:
		buffer.push_back("\treturn {type_out}(".format(idents))
		for i in dim_out:
			if signed:
				buffer.push_back("\t\tuint_to_signed_float(tmp_%d)" % i + ("," if i + 1 != dim_out else ""))
			else:
				buffer.push_back("\t\tuint_to_normalized_float(tmp_%d)" % i + ("," if i + 1 != dim_out else ""))
		buffer.push_back("\t);")

	buffer.push_back("}");
